---
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
  namespace: redhat-ods-operator
spec:
  components:
    # Required by this workshop
    dashboard:
      managementState: Managed
    kserve:
      managementState: Managed
      modelsAsService:
        managementState: Managed
      nim:
        managementState: Managed
      rawDeploymentServiceConfig: Headless
    mlflowoperator:
      managementState: Managed
    aipipelines:
      argoWorkflowsControllers:
        managementState: Managed
      managementState: Managed
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    workbenches:
      managementState: Managed
    datasciencepipelines:
      managementState: Managed
    # Not needed for the workshop
    trustyai:
      eval:
        lmeval:
          permitCodeExecution: allow
          permitOnline: allow
      managementState: Removed
    feastoperator:
      managementState: Removed
    codeflare:
      managementState: Removed
    kueue:
      managementState: Removed
    ray:
      managementState: Removed
    trainer:
      managementState: Removed
    trainingoperator:
      managementState: Removed
    trustyai:
      managementState: Removed
