apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Red Hat Connectivity Link (Kuadrant/Authorino) + cert-manager operators.
resources:
  - cert-manager-subscription.yaml
  - connectivity-link-subscription.yaml
  - kuadrant.yaml
